name: QSARModelingPy
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python
  - pygobject
  - gtk3
  - adwaita-icon-theme
  - pip
  - pip:
      - coloredlogs
      - typing_extensions
      - qsarmodelingpy
      - pyinstaller
