name: QSARModelingGUI
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.8
  - pygobject==3.30.5
  - gtk3
  - adwaita-icon-theme
  - pip
  - pip:
      - -r requirements.txt
