{% set name = "qsarmodelingpy-gui" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  path: .

build:
  entry_points:
    - qsarmodelingpy = qsarmodelingpy_gui.main:main

requirements:
  host:
    - python
    - setuptools
    - cairo
    - pycairo
    - glib
  build:
    - python
    - cairo
    - pycairo
    - glib
  run:
    - python
    - qsarmodelingpy>=0.3.0
    - cairo
    - pycairo
    - pygobject
    - typing_extensions
    - coloredlogs
    - matplotlib
    - tornado
    - pyqt
    - gtk3
    - adwaita-icon-theme


about:
  home: https://github.com/hellmrf/QSARModelingPyInterfaces
  license: GPL-v3.0
  license_familY: GPL
  license_file: LICENSE
  summary: "A software for building and validating QSAR models"
  dev_url: https://github.com/hellmrf/QSARModelingPyInterfaces

extra:
  recipe-maintainers:
    - hellmrf