name: qsarmodelingpy
version: '0.2.5'
summary: QSARModeling written in Python
description: |
    QSARModelingPy is an open source computational package to generate and validate QSAR models.
    ## What you can do with QSARModelingPy
    - Select variables through either OPS or Genetic Algorithm
    - Dimensionality reduction:
        - Correlation cut
        - Variance cut
        - Autocorrelation cut
    - Validate your models:
        - Cross Validation
        - y-randomization / Leave-N-out
        - External Validation

base: core20
grade: devel
confinement: strict

# See https://github.com/pygobject/pycairo/issues/89#issuecomment-393416874 for PyGobjects 
parts:
    qsarmodelingpy-conda:
        plugin: conda
        conda-packages:
            - -c helitonmrf
            - -c conda-forge
            - qsarmodelingpy-gui

apps:
    qsarmodelingpy:
        extensions: [gnome-3-38]
        command: bin/qsarmodelingpy
        plugs: [home]
