name: qsarmodelingpy
version: git
summary: QSARModeling written in Python
description: |
    QSARModelingPy is an open source computational package to generate and validate QSAR models.
    ## What you can do with QSARModelingPy
    - Select variables through either OPS or Genetic Algorithm
    - Dimensionality reduction:
        - Correlation cut
        - Variance cut
        - Autocorrelation cut
    - Validate your models:
        - Cross Validation
        - y-randomization / Leave-N-out
        - External Validation

base: core18
# grade: devel
confinement: strict

parts:
    qsarmodelingpy:
        plugin: dump
        source: /workdir/dist/qsarmodeling-linux.tar.xz

apps:
    qsarmodelingpy:
        extensions: [gnome-3-28]
        command: qsarmodeling
