[matplotlib]
# Here you can customize your parameters when plotting.
# For example, you can change the line width, the markers, the color, etc.
# See https://matplotlib.org/stable/tutorials/introductory/customizing.html#the-matplotlibrc-file
# The syntax is similar to the syntax in the rc file, and any option is allowed.
font.family = sans-serif
font.size = 12